version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-app}
    ports:
      - "${PORT:-8080}:80"
    environment:
      - PORT=${PORT:-8080}
    restart: unless-stopped 