/**
 * ASU Science Management
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivilegeCode } from './privilegeCode';


export interface AssignPrivilegeDto { 
    userId: string;
    privilegeCode: PrivilegeCode;
    resourceIds?: Array<string>;
}



