/**
 * ASU Science Management
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum PrivilegeCode {
    AdminPrivilege = 'ADMIN_PRIVILEGE',
    SecretaryPrivilege = 'SECRETARY_PRIVILEGE',
    StudentPrivilege = 'STUDENT_PRIVILEGE',
    DoctorPrivilege = 'DOCTOR_PRIVILEGE',
    AssistantPrivilege = 'ASSISTANT_PRIVILEGE',
    LabMaintenancePrivilege = 'LAB_MAINTENANCE_PRIVILEGE'
}

