/**
 * ASU Science Management
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PrivilegeCode } from "./privilegeCode";


export interface PrivilegeDto {
    code: PrivilegeCode;
    friendlyName: string;
    group: string;
    requiresResource: boolean;
    paramKey: string;
    entityName: string;
}
export enum PrivilegeDtoCodeEnum {
    ManageUserTypes = 'MANAGE_USER_TYPES',
    ManageUsers = 'MANAGE_USERS',
    CreateStudent = 'CREATE_STUDENT',
    StudyCourse = 'STUDY_COURSE',
    TeachCourse = 'TEACH_COURSE',
    AssistInCourse = 'ASSIST_IN_COURSE',
    LabMaintenance = 'LAB_MAINTENANCE'
};



