/**
 * ASU Science Management
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserDto { 
    name?: string;
    /**
     * Username has to be 4 letters or more
     */
    username?: string;
    password?: string;
    userTypeId?: string;
}

