/**
 * ASU Science Management
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivilegeAssignmentDto } from './privilegeAssignmentDto';


export interface UserTypeWithPrivilegeDto { 
    name: string;
    id: string;
    privileges: Array<PrivilegeAssignmentDto>;
}

